<style>
table {
    border-collapse: collapse;
	width: 100%;
}

table, th, td {
    border: 1px solid black;
	text-align: left;
	height: 30px;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
    	<section>
            <h1>Create a new entry</h1>
    
            <?php
            $this->entryForm->setAttribute('action', $this->url('book'));
            $this->entryForm->setAttribute('method', 'post');
            $this->entryForm->prepare();
            ?>
            <?php echo $this->form()->openTag($this->entryForm) ?>
        <dl>
            <dt><?php 
            $name = $this->entryForm->get('name');
            echo $this->formLabel($name); ?></dt>
            <dd><?php echo $this->formText($name) . $this->formElementErrors($name); ?></dd>

            <dt><?php echo $this->formLabel($this->entryForm->get('email')); ?></dt>
            <dd><?php echo $this->formEmail($this->entryForm->get('email')) . $this->formElementErrors($this->entryForm->get('email')); ?></dd>

            <dt><?php echo $this->formLabel($this->entryForm->get('website')); ?></dt>
            <dd><?php echo $this->formUrl($this->entryForm->get('website')) . $this->formElementErrors($this->entryForm->get('website')); ?></dd>

            <dt><?php echo $this->formLabel($this->entryForm->get('message')); ?></dt>
            <dd><?php echo $this->formTextarea($this->entryForm->get('message')) . $this->formElementErrors($this->entryForm->get('message')); ?></dd>

            <dd><?php echo $this->formSubmit($this->entryForm->get('submit')); ?></dd>
        </dl>
        <?php echo $this->form()->closeTag() ?>
        </section>
		<section>
        <h1>All recent entries</h1>
        <table style="width: 700px;">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Website</th>
            <th>Message</th>
        </tr>
        <?php foreach ($this->entries as $entry): ?>
        <tr>
            <td><?=$entry->getName()?></td>
            <td><?=$entry->getEmail()?></td>
            <td><?=$entry->getWebsite()?></td>
            <td><?=$entry->getMessage()?></td>
        </tr>
        <?php endforeach; ?>
        </table>
    </section>
	</div>
	<!-- end #page -->
</div>
