<style>
table {
    border-collapse: collapse;
	width: 100%;
}

table, th, td {
    border: 1px solid black;
	text-align: left;
	height: 30px;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
    	<section>
            <h1>Create a new entry</h1>
    
            <?php
            $this->entryForm->setAttribute('action', $this->url('book'));
            $this->entryForm->setAttribute('method', 'post');
            $this->entryForm->prepare();
            ?>
            <?=$this->form($this->entryForm);?>
        </section>
		<section>
        <h1>All recent entries</h1>
        <table style="width: 700px;">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Website</th>
            <th>Message</th>
        </tr>
        <?php foreach ($this->entries as $entry): ?>
        <tr>
            <td><?=$entry->getName()?></td>
            <td><?=$entry->getEmail()?></td>
            <td><?=$entry->getWebsite()?></td>
            <td><?=$entry->getMessage()?></td>
        </tr>
        <?php endforeach; ?>
        </table>
    </section>
	</div>
	<!-- end #page -->
</div>
