<?php echo $this->doctype(); ?>
<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  -->

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('guestbook example'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Arvo')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Coda:400,800')
                        ->prependStylesheet($this->basePath('example-theme/style.css')) ?>
    </head>
    <body>
    
    
    <!-- header -->
       <div id="menu-wrapper">
    	   <div id="menu">
        		<ul>
        			<li><a href="<?php echo $this->url('guestbook', array('action' => 'index'/*, 'parm' =>value */)); ?>">Homepage</a></li>
        			<li><a href="<?php echo $this->url('book', array('action' => 'book'/*, 'parm' =>value */)); ?>">Guest book</a></li>
        		</ul>
    	   </div>
    	<!-- end #menu -->
        </div>       
        
        <!-- content -->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
        </div>
        
        
        <!-- footer -->
        <div id="footer">
	       <p>2012. Untitled. All rights reserved. Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>. Photos by <a href="http://fotogrph.com/">fotogrph</a>.</p>
        </div>
    <!-- end #footer -->
    </body>
</html>